# Generated by Django 5.1.4 on 2024-12-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_a', models.CharField(max_length=100)),
                ('time_b', models.CharField(max_length=100)),
                ('vitorias_a', models.IntegerField()),
                ('vitorias_b', models.IntegerField()),
                ('data_jogo', models.DateField()),
            ],
        ),
    ]
