# Generated by Django 5.1.4 on 2024-12-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_casa', models.CharField(max_length=100, verbose_name='Time da Casa')),
                ('time_visitante', models.CharField(max_length=100, verbose_name='Time Visitante')),
                ('gols_casa', models.IntegerField(verbose_name='Gols do Time da Casa')),
                ('gols_visitante', models.IntegerField(verbose_name='Gols do Time Visitante')),
                ('data_partida', models.DateField(verbose_name='Data da Partida')),
            ],
        ),
        migrations.DeleteModel(
            name='Estatistica',
        ),
    ]
